grafana:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.35.237.179.126.nip.io
prometheus:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - prometheus.35.237.179.126.nip.io
